project_id = "wlfytumovijolhtlnilu"

[functions.setup-admin]
verify_jwt = false

[functions.discord-notify]
verify_jwt = false

[functions.naperis-topup]
verify_jwt = false

[functions.create-deposit-payment]
verify_jwt = false

[functions.deposit-webhook]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.distribute-leaderboard-rewards]
verify_jwt = false

[functions.notify-wishlist-flash-sale]
verify_jwt = false

[functions.send-invoice]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.api-webhook]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.process-refund]
verify_jwt = false

[functions.extract-sticker-zip]
verify_jwt = false

[functions.smm-api]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-search-suggest]
verify_jwt = false

[functions.seller-webhook-dispatch]
verify_jwt = false

[functions.bulk-import-products]
verify_jwt = false

[functions.domain-checker]
verify_jwt = false

[functions.video-downloader]
verify_jwt = false

[functions.mail-checker]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false
